### ISSUE TITLE
Get Thing from Thing Directory

### ISSUE THREAD

**Issue by Serge3006** [oeg-upm/wot-hive#13]
When we apply the following query:

curl http://localhost:9000/api/things/urn:dev:testId10

We get the following error:

{
        "code": "WOT-DIR-P",
        "description": "TD with the given id not found",
        "detail": "directory.exceptions.ThingNotFoundException: Requested Thing not found"
}

**Comment by AndreaCimminoArriaga** [comment]
Please could you provide the TD as well?

**Comment by Salva5297** [comment]
When  we make a PUT operation into the Wot-Hive storing a specific TD we cannot retrieve that TD by the ID.
The example TD is the following:

```
{
  "@context": [
    "https://www.w3.org/2019/wot/td/v1", 
    {
      "beo": "https://pi.pauwel.be/voc/buildingelement#", 
      "bot": "https://w3id.org/bot#", 
      "brick": "https://brickschema.org/schema/1.1/Brick#", 
      "om": "http://openmetrics.eu/openmetrics#", 
      "props": "https://w3id.org/props#", 
      "rdfs": "http://www.w3.org/2000/01/rdf-schema#", 
      "xsd": "http://www.w3.org/2001/XMLSchema#"
    }
  ], 
  "@id": "data.cogito.iot.linkeddata.es/thing/cogito1212", 
  "@type": [
    "bot:Building", 
    "brick:Building"
  ], 
  "description": "A building element.", 
  "properties": {
    "IfcFile": {
      "forms": [
        {
          "href": "https://example_uri.com/files/cogito1212",
		  "type": "multipart-form/data"
        }
      ]
    }, 
    "RDFUri": {
      "forms": [
        {
          "href": "https://openmetrics.eu/openmetrics#Building_120",
		  "type": "text/turle"
        }
      ]
    }
  }, 
  "security": [
    "no_sec"
  ], 
  "securityDefinitions": {
    "no_sec": {
      "scheme": "nosec"
    }
  }, 
  "title": "cogito1212"
}
```

**Comment by AndreaCimminoArriaga** [comment]
When I register this TD I get a json payload with the error, that boils down to following response:

````
[...] Not a valid (absolute) IRI: /data.cogito.iot.linkeddata.es/thing/cogito1212 [line 1]\"}"
````
You are using as id a relative IRI `data.cogito.iot.linkeddata.es/thing/cogito1212` that is now allowed. Using an absolute IRI the Wot Hive works properly, e.g., `http://data.cogito.iot.linkeddata.es/thing/cogito1212` 

**In addition, in the next release if the PUT is performed to http://localhost:9000/api/things/urn:dev:testId10 then the id of the TD shall be urn:dev:testId10**. This issue is been closed since the issue was not with the code. Thanks for posting the issue.
